# Generated by Django 4.2.7 on 2024-01-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_financialrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='email',
            field=models.EmailField(default=56789, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='email',
            field=models.EmailField(default=23, max_length=254),
            preserve_default=False,
        ),
    ]
